### ISSUE TITLE
Support 5 parameter easing functions

### ISSUE THREAD

**Issue by jaxgeller** [callmecavs/jump.js#1]
Like this

```
var jumper = new Jumper({
  easing: function (x, t, b, c, d) {
    if ((t/=d/2) < 1) return c/2*t*t*t + b;
    return c/2*((t-=2)*t*t + 2) + b;
  }
});
```

**Comment by jaxgeller** [comment]
Actually just make it clear that if you use the recommended easing functions, you need to drop `x`. or just support `x` param.

**Comment by callmecavs** [comment]
per the new API custom easing isn't support. easeInOutQuad for the win
