### ISSUE TITLE
Readme typo: Instance, instantialize

### ISSUE THREAD

**Issue by BrainCrumbz** [callmecavs/jump.js#11]
Just a couple of suggestions in readme.md, mainly a matter of wording. 
1. There's a section named [_Instance_](https://github.com/callmecavs/jump.js#instance), that maybe could be named something like _Instantiate_ or _Create_ or _Initialize_, to keep it aligned with the other two sections, that seem to be verbs (_Install_, _Jump_)
2. In that same section, it says _instantialize_, which I guess could be something like _initialize_ or _instantiate_.

HTH. Regards,
The BrainCrumbz Team

**Comment by callmecavs** [comment]
someone raised this issue on Reddit too haha, will definitely fix this. thanks for bringing it to my attention
