### ISSUE TITLE
Using with Meteor JS

### ISSUE THREAD

**Issue by Rajan** [callmecavs/jump.js#13]
I'd like to use it with Meteor.
Is it possible to add as npm module and use it?
npm modules are accessible only on server with standard methods.
How can I use Jump.js with Meteor?

**Comment by callmecavs** [comment]
the instructions to install jump.js from NPM are here: https://github.com/callmecavs/jump.js#install

the library is contained within a UMD wrapper, which supports Common JS (Node's module format), so in theory, it should work within Node - and thus Meteor.

i've never used Meteor myself, so beyond this, I'm afraid I can't be much help. good luck!
