### ISSUE TITLE
Focus management

### ISSUE THREAD

**Issue by Heydon** [callmecavs/jump.js#16]
It's not clear from the documentation that focus management is supported. That is, when jumping to a selector, this element would be focused so that keyboard interaction is localized to the newly "jumped to" element.

If this is not supported, I suggest there is an accessibility issue for keyboard and AT users and would be happy to answer any questions you might have about addressing it.

Thanks!

**Comment by callmecavs** [comment]
the library doesn't currently do anything to manage the focus. in terms of addressing accessibility, and focusing the target after the jump is complete, is it as simple as calling `.focus()` on the element that's been scrolled to? i'm a bit naive when it comes to accessibility so I'd appreciate your input.

in the case of scrolling a fixed pixel amount, rather than to an element, is there anything in particular that should be focused in that case? or is it best to just retain focus on what was previously focused?

**Comment by callmecavs** [comment]
ping @Heydon

**Comment by Heydon** [comment]
Hey Michael. Yeah, the element that is animated to should be focused at the
end of the animation (callback function, maybe?) The element should be made
programmatically focusable by giving it tabindex="-1" before you use the
focus() method on it. Hope that helps. Ask if you need anything more :-)

**Comment by callmecavs** [comment]
sounds good, i'll take a shot at implementing this in the `_end()` method. this is the method that fires the callback, at the end of the jump

**Comment by Heydon** [comment]
Oh, that sounds perfect. Nice one!

**Comment by callmecavs** [comment]
does `-1` or `0` make more sense for the tabindex? looking at [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex), it seems as though `0` may be the better choice, because a negative value means the element would be otherwise unreachable by keyboard navigation

**Comment by Heydon** [comment]
-1 means focusable but only programmatically. This is suitable because
you're only focusing the element to move the user into the right area. 0
would mean the element is permanently focusable, which would not be
suitable because (typically) it would not be an interactive element like a
link or button; just a container. Does that make sense?

**Comment by callmecavs** [comment]
makes perfect sense. thanks for the great explanation. really happy you raised this issue. admittedly im not an expert on accessibility support - knowing i can add something like this to provide it is awesome

**Comment by callmecavs** [comment]
@Heydon running into a problem with adding a `tabindex` and calling `focus()` on the element - browsers draw a blue outline around the element, like they would a form element, as seen in the screenshot below. is there any way you know of to avoid this?

<img width="1028" alt="screen shot 2015-12-02 at 11 09 44 pm" src="https://cloud.githubusercontent.com/assets/2293641/11551777/71ae9bba-994a-11e5-85f4-38b9ad23dcb0.png">

**Comment by callmecavs** [comment]
the code for this is on the focus branch if you want to play around with it: https://github.com/callmecavs/jump.js/tree/focus

**Comment by ZoeBijl** [comment]
There are a few ways around this. The _**absolute worst**_—how do I stress this further?—thing to do is to disable the outline:

`element:focus { outline: none }`

A better way to do it is to animate that outline into oblivion on focus:

```
element:focus {
  animation: outline 2s;
}

@keyframes outline {
  to {
    outline-color: transparent;
  }
}
```

Another option that involves animation, but allows you to “make things prettier”: you can animate anything you want on focus. So you could disable the outline—contradicting what I said earlier; the important thing is that focus is visible—on the focused element, but animate the background from a noticeable different colour—say yellow—to the original colour—say white—and thus make it clear where focus went on the page.

You could of course also drop the animation and make focus noticeable permanently, but that is a design choice.

**Comment by Heydon** [comment]
I actually disagree here. Tabindex="-1" programmatically focused elements
don't necessarily need a focus style. That the element / area is pulled
into view is enough. You can, however, get creative with animated focus
styles. Perhaps this should be communicated to potential authors?

**Comment by ZoeBijl** [comment]
After thinking about it for a bit, that makes sense. I use animated focus styles for skip links, but not consistently it seems. I thought I read a WebAIM article on it once, but can only find one that advises to [use `animation` to keep (hidden) skip links visible](http://webaim.org/techniques/skipnav/) for a short period after you've focused them.

It would be good to add this to the documentation. Maybe something like:

> ## Focus management
> 
> To aid keyboard and assistive technologies (AT) users; it is important that focus is moved to the scrolled to element. Jump.js does this automagically. By default visual aids of focus are disabled. Authors are free to enable such aids via CSS.

What would happen if an author uses Jump.js to scroll to an interactive element?

**Comment by callmecavs** [comment]
my preference would be to include as little CSS in the library as possible. im happy to set `outline: none` on the element that's jumped to from the JS, but don't want to make a stylesheet required to use the library.

i'm leaning towards the solution above - adding the `tabindex`, calling `focus()`, disabling the outline, and mentioning accessibility in the README. that seems to be in line with both of your thinking - does this seem like a reasonable solution?

**Comment by ZoeBijl** [comment]
If there was something that prevented the outline being disabled on interactive elements; I would agree to that resolution.

CSS could look something like this—probably forgot a couple:

```
[tabindex="-1"]:not(a, input, button, textarea, select, [role*="button"]) {
  outline: none;
}
```

This is compliant with Jump.js' browser support.

**Comment by callmecavs** [comment]
I only want to use CSS that I can control from JS, using the `style` prop on the element nodes. that rule requires getting more than just the element scrolled to, and injecting into the `<head>`, etc

much easier and cleaner to just do `target.style.outline = 'none'` and then make a note about it in the README

**Comment by ZoeBijl** [comment]
Fair enough. It would be possible to check against the same list in JavaScript right? Some automation is desirable I think.

**Comment by callmecavs** [comment]
@Heydon are thoughts on focusing the target element, and setting `outline: none` on it?

also, congrats on getting into the collective with your [flexbox writeup](https://medium.com/@Heydon/flexbox-grid-finesse-4d22b80bfee1#.tbwylep23), Jump is in it this week as well :beers:

**Comment by callmecavs** [comment]
@MichielBijl if users are jumping to a form element, they can restore the outline in the callback function. rather than disable the outline for everything in that selector with JS, it'd be easier to just disable it on the target, and let the user re-enable it in the callback if necessary. what're your thoughts on that?

**Comment by Heydon** [comment]
Oh, thanks! What's the collective?

I think I would personally just leave it to the author to remove that
outline if they so wished. That saves you from having to dirty your hands
with js/css.

**Comment by ZoeBijl** [comment]
I'm with Heydon on this; some documentation or a reference to this issue, could help authors with understanding the issue with focus outlines. If that is a no go for what ever reason, `target.style.outline = 'none'` should do fine with a clear warning in the documentation.

**Comment by callmecavs** [comment]
@Heydon Tympanus/Codrops does it - it's a weekly roundup of web design and development projects. here's the link to this weeks (that we're both in): http://tympanus.net/codrops/collective/collective-197/

@Heydon @MichielBijl okay, i guess I'll take a stab at not touching the outline and letting people handle it themselves. feel like it may lead to a lot of questions tho

**Comment by callmecavs** [comment]
@Heydon will be included in v1, behind a flag. the only reason for me disabling it by default is because it requires a CSS change to prevent the blue outline

**Comment by Heydon** [comment]
Okay, thanks for letting me know!

**Comment by callmecavs** [comment]
@Heydon thanks for bringing it up, and hashing it out with me. my apologies for it taking so long to add

**Comment by Heydon** [comment]
0pp0p00p00pp00p00000000
---------- Forwarded message ----------
From: "Sidebar" <hello@sidebar.io>
Date: 29 Dec 2017 17:04
Subject: Get Taxi, Trainline UX, Range Input, Worst Reviewed, 2017 Case
Studies
To: <heydon@heydonworks.com>
Cc:

The 5 best design links, every day. Curated by a selection of great
editors.
[image: Sidebar]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=913710426d&e=dd1dd5a5cb>
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=05eb0917bc&e=dd1dd5a5cb>
UI/UX Case Study : A Brand New "Get Taxi Experience"
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=e51f9793cc&e=dd1dd5a5cb>
medium.com
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=ac1dd32ab1&e=dd1dd5a5cb>

I tested the existing "GetTaxi" app with 10 participants in problematic
pickup areas around Tel Aviv.
Case Study UX

Submitted by Sacha Greif
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=901fa80875&e=dd1dd5a5cb>
[image: Share by email]
<?subject=Interesting%20link%3A%20UI%2FUX%20Case%20Study%20%3A%20A%20Brand%20New%20%22Get%20Taxi%20Experience%22&body=I%20thought%20you%20might%20find%20this%20interesting%3A%0A%0AUI%2FUX%20Case%20Study%20%3A%20A%20Brand%20New%20%22Get%20Taxi%20Experience%22%0Ahttps%3A%2F%2Fmedium.com%2Fswlh%2Fui-ux-case-study-a-brand-new-get-taxi-experience-6c43c7c815fa%0A%0A(found%20via%20null)%0A%20%20>
[image:
Share on Twitter]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=abca685b46&e=dd1dd5a5cb>
[image:
Share on Facebook]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=39ab5bf677&e=dd1dd5a5cb>
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=a85f680ad8&e=dd1dd5a5cb>
Have Trainline nailed their UX?
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=eb83c4b799&e=dd1dd5a5cb>
uxplanet.org
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=8322a2b5d5&e=dd1dd5a5cb>

Quick feature thoughts and improvements for the Trainline app.
Critique UX

Submitted by Sacha Greif
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=ffacbb3b3d&e=dd1dd5a5cb>
[image: Share by email]
<?subject=Interesting%20link%3A%20Have%20Trainline%20nailed%20their%20UX%3F&body=I%20thought%20you%20might%20find%20this%20interesting%3A%0A%0AHave%20Trainline%20nailed%20their%20UX%3F%0Ahttps%3A%2F%2Fuxplanet.org%2Fhave-trainline-nailed-their-ux-7694e6f16897%0A%0A(found%20via%20null)%0A%20%20>
[image:
Share on Twitter]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=6d0a3ea562&e=dd1dd5a5cb>
[image:
Share on Facebook]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=567c148e26&e=dd1dd5a5cb>
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=9ed114fd57&e=dd1dd5a5cb>
A Sliding Nightmare: Understanding the Range Input
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=1bd9e5a4dd&e=dd1dd5a5cb>
css-tricks.com
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=441e984d36&e=dd1dd5a5cb>

You may have already seen a bunch of tutorials on how to style the range
input.
CSS

Submitted by Sacha Greif
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=b54a98d86b&e=dd1dd5a5cb>
[image: Share by email]
<?subject=Interesting%20link%3A%20A%20Sliding%20Nightmare%3A%20Understanding%20the%20Range%20Input&body=I%20thought%20you%20might%20find%20this%20interesting%3A%0A%0AA%20Sliding%20Nightmare%3A%20Understanding%20the%20Range%20Input%0Ahttps%3A%2F%2Fcss-tricks.com%2Fsliding-nightmare-understanding-range-input%2F%0A%0A(found%20via%20null)%0A%20%20>
[image:
Share on Twitter]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=e555d14e43&e=dd1dd5a5cb>
[image:
Share on Facebook]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=7b3d5b115a&e=dd1dd5a5cb>
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=53ce1c6656&e=dd1dd5a5cb>
The Best and Worst Identities of 2017, Part 3: The Worst Reviewed
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=6108f615d9&e=dd1dd5a5cb>
underconsideration.com
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=42b1e703f0&e=dd1dd5a5cb>

Each year this list gets less and less juicy with very few clunkers, which
is a good thing for our visual environment.
Branding

Submitted by Sacha Greif
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=002161e002&e=dd1dd5a5cb>
[image: Share by email]
<?subject=Interesting%20link%3A%20The%20Best%20and%20Worst%20Identities%20of%202017%2C%20Part%203%3A%20The%20Worst%20Reviewed&body=I%20thought%20you%20might%20find%20this%20interesting%3A%0A%0AThe%20Best%20and%20Worst%20Identities%20of%202017%2C%20Part%203%3A%20The%20Worst%20Reviewed%0Ahttps%3A%2F%2Fwww.underconsideration.com%2Fbrandnew%2Farchives%2Fthe_best_and_worst_identities_of_2017_part_3_the_worst_reviewed.php%0A%0A(found%20via%20null)%0A%20%20>
[image:
Share on Twitter]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=51eef139cd&e=dd1dd5a5cb>
[image:
Share on Facebook]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=59be6d04e2&e=dd1dd5a5cb>
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=82b47865a9&e=dd1dd5a5cb>
Case Studies: Best of 2017
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=5293dc02c2&e=dd1dd5a5cb>
medium.com
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=aa49692952&e=dd1dd5a5cb>

When reading through design case studies we get to go on a trip with the
designer and follow their trail of thought.
Case Study

Submitted by Jan Wennesland
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=3b7d688090&e=dd1dd5a5cb>
[image: Share by email]
<?subject=Interesting%20link%3A%20Case%20Studies%3A%20Best%20of%202017&body=I%20thought%20you%20might%20find%20this%20interesting%3A%0A%0ACase%20Studies%3A%20Best%20of%202017%0Ahttps%3A%2F%2Fmedium.com%2Fcase-study-club%2Fcase-studies-best-of-2017-a0c77855c541%0A%0A(found%20via%20null)%0A%20%20>
[image:
Share on Twitter]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=ae7a2566e0&e=dd1dd5a5cb>
[image:
Share on Facebook]
<https://sidebar.us2.list-manage.com/track/click?u=b5af47765edbd2fc173dbf27a&id=1493326f78&e=dd1dd5a5cb>


Sacha Greif - Paris, France






This email was sent to heydon@heydonworks.com
*why did I get this?*
<https://sidebar.us2.list-manage.com/about?u=b5af47765edbd2fc173dbf27a&id=9abeab36bb&e=dd1dd5a5cb&c=7c9a297f59>
    unsubscribe from this list
<https://sidebar.us2.list-manage.com/unsubscribe?u=b5af47765edbd2fc173dbf27a&id=9abeab36bb&e=dd1dd5a5cb&c=7c9a297f59>
    update subscription preferences
<https://sidebar.us2.list-manage.com/profile?u=b5af47765edbd2fc173dbf27a&id=9abeab36bb&e=dd1dd5a5cb>
Sacha Greif · --- · Paris - · France

**Comment by Heydon** [comment]
Ppp0
---------- Forwarded message ----------
From: "Trainline" <trainline@news.thetrainline.com>
Date: 14 Jan 2018 6:08 p.m.
Subject: Your journey to London Liverpool Street tomorrow
To: <heydon@heydonworks.com>
Cc:


Important last minute information for your journey from Norwich to London
Liverpool Street
View online
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe519&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512&p1=E7Cp7opzeu3yy1KzkK7d6yV7dJZbj9xL>

<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe51a&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>
Heydon's account
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe539&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe53a&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>


Download App
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe53b&action=click&publisher_id=168964&site_id_web=115239&site_id_iOS=101908&site_id_android=103816&my_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&my_adgroup=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>
•
Best Fare Finder
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe53c&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>
•
Ticket Alert
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe53d&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>

[image: Are you ready?]
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe53e&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>

*Heydon, charge your mobile phone!*

Remember to activate your mobile ticket before your trip on the day of
travel - this will be waiting for you in your Trainline app.

*Mobile ticket FAQ*
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe542&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>

*Out* Monday 15 January

15:00


16:57
Norwich
(Greater Anglia)

London Liverpool Street


*Return* Tuesday 16 January

10:00


11:50
London Liverpool Street
(Greater Anglia)

Norwich




If you recently made changes to your booking, visit *My Account*
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe543&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>
for your up-to-date journey details.

*Stay one step ahead*

Get our app and you're ready for anything, with live delay, departure and
platform info.

*Download the app now*
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe546&action=click&publisher_id=168964&site_id_web=115239&site_id_iOS=101908&site_id_android=103816&my_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&my_adgroup=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>

<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe547&action=click&publisher_id=168964&site_id_web=115239&site_id_iOS=101908&site_id_android=103816&my_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&my_adgroup=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>

*Don't forget your... umbrella*

We think you'll need it when you get to London on Monday.




*Max: 10°CMin: 6°C*   *Rain*


*Station Details*

Our handy station guides help you find facilities and plan a quick exit.

*Norwich *
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe548&p1=www.thetrainline.com/stations/norwich>
*London Liverpool Street*
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe549&p1=www.thetrainline.com/stations/london-liverpool-street>





Rate our email:
[image: 1 star rating]
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe54a&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512&p1=%40eWA9QUqp9EyQtuPwMOtxyg%3D%3D>
[image:
2 star rating]
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe54b&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512&p1=%40eWA9QUqp9EyQtuPwMOtxyg%3D%3D>
[image:
3 star rating]
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe54c&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512&p1=%40eWA9QUqp9EyQtuPwMOtxyg%3D%3D>
[image:
4 star rating]
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe54d&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512&p1=%40eWA9QUqp9EyQtuPwMOtxyg%3D%3D>
[image:
5 star rating]
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe54e&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512&p1=%40eWA9QUqp9EyQtuPwMOtxyg%3D%3D>

*Follow us: *
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe54f>
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe550>

*Please do not reply to this email as we will not be able to respond.*



*Registered address and tax*
Trainline.com Limited is a company registered in England (with company
registration number 3846791).
Our registered office is at: 120 Holborn, London EC1N 2TD. Trainline.com
Limited is registered with VAT number 791 7261 06, however, train tickets
are currently zero rated for VAT and so VAT receipts are not routinely
offered. You can contact our customer services department by using the
contact details supplied on the contact us page
<http://t.news.thetrainline.com/r/?id=h393d4d79,394628,23dfe551&utm_medium=email&utm_source=trigger&utm_campaign=TL_L_Pre-Departure%20Trigger%20-%20PD3%20-%201&utm_content=TL_L_2016_05_25_PRG_PreDeparture_Email_3_OptOut_LEG%7C3753512>.
thetrainline is a trading name of Trainline.com Limited.
