### ISSUE TITLE
Arrow Functions & IE

### ISSUE THREAD

**Issue by Japegrape** [callmecavs/jump.js#22]
You claim IE 10+ support, yet you're using arrow function notation, which isn't supported in any version of IE:

http://caniuse.com/#feat=arrow-functions

Am I missing something?

**Comment by callmecavs** [comment]
@Japegrape yes - the library is transpiled to ES5 syntax using Babel. check the [JS task in the gulpfile](https://github.com/callmecavs/jump.js/blob/master/gulpfile.babel.js#L33-L67).

if you're not familiar with transpiling - basically it allows the luxury of writing in the future syntax, but converts (compiles down) the code to the current syntax, for compatibility in current browsers.
