### ISSUE TITLE
Support for scrolling inside elements

### ISSUE THREAD

**Issue by straku** [callmecavs/jump.js#23]
Did you think about adding support for scrolling inside elements? I think that it could be used like this:

```
Jump.jump('.selector', {
  duration:500,
  container: '.widget'
})
```

I know that it would require rather significant changes in the way that scrolling is handled, but maybe it is a nice idea for future improvements.

**Comment by callmecavs** [comment]
will definitely consider it for a future enhancement - not sure the juice is worth the squeeze though, because I think the predominant use case for smooth scrolling is in relation to the page.  added the enhancement label, will put some thought into it

**Comment by straku** [comment]
Don't think about it in terms of simple websites (like landing pages) but rather _SPA_. In my experience it is quite common to have fixed navbar and menu and all of application elements in a single panel. With scrolling on `window` object it is impossible to use `Jump.js` in this situation. There are other libraries that support this behavior ([example](https://github.com/madebysource/animated-scrollto)) but I really, really, really like the simplicity of `Jump.js` and its _ES6_ support, so please consider this enhancement. Fingers crossed!

**Comment by callmecavs** [comment]
fair point about SPAs, definitely worth supporting them if possible.  I'll likely implement it, but it might be a week or 2 down the road

**Comment by mrenty** [comment]
I added this enhancement with fallback for the `window`, and prepared [PR #24](https://github.com/callmecavs/jump.js/pull/24) for this.

**Comment by callmecavs** [comment]
please see #31, and leave your feedback!
