### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by callmecavs** [callmecavs/jump.js#31]
Is on the way!

The following will **absolutely be included**:
1. follow the singleton pattern, and take a purely functional approach ([no instantiation necessary](https://github.com/callmecavs/jump.js/issues/28))
2. [accessibility](https://github.com/callmecavs/jump.js/issues/16), behind an option (boolean/flag), because it requires CSS to prevent a default blue `outline` from showing on the element that's scrolled to
3. [unminified version of dist file](https://github.com/callmecavs/jump.js/issues/26)
4. better target resolution (accept px value, node or CSS selector) - #30, #29

The following are **under consideration**:
- support scrolling within an element (aka not the `window` object)
  - may bloat the lib, by requiring a different "top of element" calculation, and different loop to scroll the container element

I cant thank the users of this library enough for making it as popular as it is - please leave your thoughts, and feature requests, on this issue. and please dont take offense to me closing your issue/pull request - hopefully ive addressed it here (or left if open).

its easier for me to have everything under "one roof". cheers to all 🍻 

follow the progress on the [v1.0.0 branch](https://github.com/callmecavs/jump.js/tree/v1.0.0)

**Comment by callmecavs** [comment]
**update:** 1, 2, and 4 are done. see the [v1.0.0 branch](https://github.com/callmecavs/jump.js/tree/v1.0.0)

the dist file is almost half the size (1.44kb vs 2.7kb) - compliments of the functional approach, and upgraded build system

the [gulpfile](https://github.com/callmecavs/jump.js/blob/v1.0.0/gulpfile.js) is now using [rollup](https://github.com/rollup/rollup) by @Rich-Harris. find more by him on [GitHub](https://github.com/Rich-Harris), and on [GitLab](https://gitlab.com/Rich-Harris/)

**Comment by mgiulio** [comment]
+1 :)

If I'll be able to find some time I'll try to help.

**Comment by callmecavs** [comment]
@mgiulio you already helped by writing the [SitePoint article](http://www.sitepoint.com/smooth-scrolling-vanilla-javascript/). using the singleton pattern was your idea. it made so much sense, i had to implement it in v1.0.0

i appreciate both the article, and the thinking about how the library could be better. you'll be mentioned in the v1.0.0 release notes

**Comment by mrksbnch** [comment]
Personally, I would love to see support for scrolling within an element. I don't see why this would bloat the library though. Instead of [`scrollTo()`](https://developer.mozilla.org/en/docs/Web/API/Window/scrollTo), you'd have to use [`scrollTop`](https://developer.mozilla.org/en/docs/Web/API/Element/scrollTop), but that's most likely done in a couple of extra lines. If it helps, I could create a pull request for this feature in the [v1.0.0 branch](https://github.com/callmecavs/jump.js/tree/v1.0.0).

**Comment by martin-svk** [comment]
What is the timeline in which we can expect the release of 1.0? Thanks

**Comment by callmecavs** [comment]
@mgiulio @mrksbnch @martin-svk its been released! see the [release notes](https://github.com/callmecavs/jump.js/releases/tag/v1.0.0)
