### ISSUE TITLE
Instantiate code example in readme doesn't run

### ISSUE THREAD

**Issue by TheTedAdams** [callmecavs/jump.js#34]
```
// import Jump
import Jump from 'jump.js'

// create an instance
const Jump = new Jump()
```

This code run through babel gets the error: `Module build failed: TypeError: [filenamehere]: Duplicate declaration "Jump"`

The const name can't match the name of the imported default export.

**Comment by callmecavs** [comment]
Good catch. Should be:

```
const jump = new Jump()
```

Feel free to open a PR. Otherwise this will get fixed in the [v1.0.0 release](https://github.com/callmecavs/jump.js/issues/31).
