### ISSUE TITLE
adding a selector for target error

### ISSUE THREAD

**Issue by nevinlaughlin** [callmecavs/jump.js#36]
I may have found a bug... trying to pass a selector in I get this error, Uncaught TypeError: target.getBoundingClientRect is not a function, because target is a string on line 20.

on line 20 of jump js
 should it be 
`: this.options.offset + this.target.getBoundingClientRect().top;`
instead of
`: this.options.offset + target.getBoundingClientRect().top;`

http://codepen.io/nevinlaughlin/pen/zBqpwe

Thanks, love the script!!

Sorry, this may have been a duplicate find.

**Comment by callmecavs** [comment]
@nevinlaughlin its addressed in the v1.0.0 branch 👍 not released yet (haven't had time) but the code is working, and available on that branch 🍻
