### ISSUE TITLE
Double clicking arrows causing animation to fire twice

### ISSUE THREAD

**Issue by davereid91** [callmecavs/jump.js#42]
Hello,

I am not sure if this is an issue with the library itself or just with the demo page but double clicking the arrows causes the scrolling animation to replay twice. It will do the initial scroll down, jump back to the top and then scroll down again. Just thought I would give a heads up :)

**Comment by yuraxdrumz** [comment]
Hey! just saw your little project, love the idea, a possible solution would be to disable the click button as soon as you click on it, and enable it after the the scroll has been completed, just an idea :)

**Comment by callmecavs** [comment]
@davereid91 the best solution here is to handle throttling the click event externally, as @yuraxdrumz describes. I built the demo page in a hurry 😉, small oversight on my part haha

**Comment by hendrikeng** [comment]
hey there, i am having a similar issue, cant i i.e set a variable animationInProgress = true , and callback it to false if the scrollevent is finished? i can't make it work somehow.
