### ISSUE TITLE
No module export

### ISSUE THREAD

**Issue by necrower** [callmecavs/jump.js#53]
Can't import cause no module are exported.

**Comment by callmecavs** [comment]
@necrower have a feeling this is specific to your build configuration - what tools are you using, and how are you including jump?

**Comment by necrower** [comment]
I've tried use with Angular 2 new project.

**Comment by callmecavs** [comment]
@necrower probably going to need more detail than that - especially considering this is a vanilla JS project and you're asking about use with Angular.

again, what tools, how is the library included, etc
