### ISSUE TITLE
It is a nightmare to use this with my angular 2 application using system js for bundling

### ISSUE THREAD

**Issue by nickthakkar** [callmecavs/jump.js#54]
**Here is how my system js config looks:** 
 System.config({
      defaultJSExtensions: true,
      map: {
        '@angular':    'node_modules/@angular',
        'rxjs':        'node_modules/rxjs',
        'moment':      'node_modules/moment',
        'lodash':      'node_modules/lodash',
        'ts':          'node_modules/plugin-typescript/lib/plugin.js',
        'typescript':  'node_modules/typescript/lib/typescript.js',
        'jump':      'node_modules/jump.js'
      },
      packages: {
        '@angular/common': {main: 'bundles/common.umd.js'},
        '@angular/compiler': {main: 'bundles/compiler.umd.js'},
        '@angular/core': {main: 'bundles/core.umd.js'},
        '@angular/forms': {main: 'bundles/forms.umd.js'},
        '@angular/http': {main: 'bundles/http.umd.js'},
        '@angular/platform-browser': {main: 'bundles/platform-browser.umd.js'},
        '@angular/router': {main: 'bundles/router.umd.js'},
        '@angular/platform-browser-dynamic': {main: 'bundles/platform-browser-dynamic.umd.js'},
        'jump': {main: 'dist/jump.js'},
        'lodash': {main: 'lodash.js'},
        'less': { main: 'less.js' },
        'bootstrap': 'bootstrap.js'
      }
    });

**importing this in one my angular component like this doesn't work:** 

import * as jump from 'jump';

**Comment by callmecavs** [comment]
great example here of how not to get help here with something that is **particular to your use case**.

also, read the README. for starters, check your `import` statement. the package name is incorrect, and there's only 1 default export. so, at the very least, this:

```
import * as jump from 'jump'
```

has 2 errors, and should be:

```
import jump from 'jump.js'
```

try making sure your importing correctly before dumping in your system JS config unformatted into the issue description like it has something to do with the library
