### ISSUE TITLE
Is it possible to use Jump to replace the default behavior for the anchors?

### ISSUE THREAD

**Issue by aminta** [callmecavs/jump.js#58]
Like: https://github.com/flesler/jquery.localScroll

"If you want to convert the links from ALL over the page, with the same settings, just call $.localScroll(...) instead of $(...).localScroll(...)"

Thanks!

**Comment by callmecavs** [comment]
I'm not sure - I've never used that plugin.  Out of the box, `jump` doesn't do anything automatically, and it looks like `localScroll` tries to provide automatic scroll management of hash links.
