### ISSUE TITLE
Can we use GSAP Easings with Jump.js ?

### ISSUE THREAD

**Issue by proov** [callmecavs/jump.js#67]
I'm already using GSAP on my project, i'd like to use their easings. I tried this but it doesn't seems to work 😁 

``` javascript
/**
 * Jump.js
 */

import Jump from 'jump.js'
import { Power4 } from 'gsap'

// All Jump Links
const links = document.querySelectorAll('[data-jump]')

// For Each Link
// They must have a valid anchor in href attr
for (let link of links) {

  link.addEventListener('click', (ev) => {

    ev.preventDefault()
    let dest = link.getAttribute('href')
    Jump(dest, {
      duration: 1000,
      easing: Power4.easeOut,
    })
  })

}
```

**Comment by callmecavs** [comment]
@proov cant say for certain because I dont use GSAP - that being said there are a bunch of easing functions [here](https://github.com/jaxgeller/ez.js/blob/master/ez.js) that follow the parameter order of the default easing used in the library.

**Comment by proov** [comment]
Yeah i used `ez.js`, nice package !
