### ISSUE TITLE
Doesn't work with gulp?

### ISSUE THREAD

**Issue by tr1s** [callmecavs/jump.js#68]
Does this not work with gulp? I'm trying everything and I just keep getting a 'jump is not defined' error.

**Comment by callmecavs** [comment]
Make sure you `import`/`require` like so:

```javascript
// note the .js at the end of the package name

import jump from 'jump.js'

// or

const jump = require('jump.js')
```

If that isn't the fix, it's likely something else with how your build system is setup.
