### ISSUE TITLE
An old scholl version, really..

### ISSUE THREAD

**Issue by stratboy** [callmecavs/jump.js#71]
Hi, your script is stellar, thank you. But I think you should really release even an 'old school', non-modern workflows, where old school scripts are used as well and mergerd together. It's really a pity to make it unusable in such environments.

**Comment by callmecavs** [comment]
@stratboy if by old school you mean using it as a `script` tag without running a module bundler, just use it via [unpkg](https://unpkg.com/#/).

put this at the bottom of your HTML document, just before the `</body>` tag:

```html
<script src="https://unpkg.com/jump.js@1.0.2/dist/jump.js"></script>
```

and the library will be available on the `window` object as `Jump`.

this works for most packages on npm - just keep in mind distribution files might not always be compiled down to ES5

**Comment by stratboy** [comment]
So, I need to merge js files, so I exctracted the unpkg code into a jump.js file and merged it on my main js file (loaded in footer of course).
For some reason, easeInOutQuad results undefined. I don't know why, it's in the code, and if I trace it from jump.js I see it in console, but it's undefined when I later call Jump.





Michael Cavalea ha scritto:
