### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by smokills** [callmecavs/jump.js#9]
Hi!
First of all tanks for your work. I really appreciate this plugin. But could you add even the bower support?
Thanks :D

**Comment by petehouston** [comment]
@callmecavs are you adding it to bower registry? If not, I can give a hand if okay.

**Comment by callmecavs** [comment]
really torn here. I'm an ES6 proponent, and this is an ES6-first project. I believe that NPM isn't only for Node packages anymore. I'd like to encourage people transitioning to a modern workflow (ES6, module bundling), and away from script tags. Bower also doesn't support nested dependencies, which for this library isn't an issue, but is for many others. in all likelihood, projects using Bower are also using NPM, and for that reason as well as the others, I'm opting to no longer support Bower with my libraries.

on the other hand, I do understand making the library as accessible as possible. for that reason, I package my `dist` files as a UMD module, which can be run directly in the browser, with a simple script tag. my recommendation would be to use it that way, if not with NPM. I do appreciate your input tho

if you'd like to consider making the transition to an entirely NPM & ES6 workflow, take a look at my minimal boilerplate [outset](https://github.com/callmecavs/outset) and let me know if you run into any implementation trouble
